In [1]:
import pandas as pd

In [2]:
population = pd.read_csv('world_population.csv',
                         parse_dates=True, index_col = 'Year')

# Upsample population
population.resample('A').first()

            Total Population
Year
1960-12-31      3.034971e+09
1961-12-31               NaN
1962-12-31               NaN
1963-12-31               NaN
1964-12-31               NaN
1965-12-31               NaN
1966-12-31               NaN
1967-12-31               NaN
1968-12-31               NaN
1969-12-31               NaN
1970-12-31      3.684823e+09
1971-12-31               NaN
1972-12-31               NaN
1973-12-31               NaN
1974-12-31               NaN
1975-12-31               NaN
1976-12-31               NaN
1977-12-31               NaN
1978-12-31               NaN
1979-12-31               NaN
1980-12-31      4.436590e+09
1981-12-31               NaN
1982-12-31               NaN
1983-12-31               NaN
1984-12-31               NaN
1985-12-31               NaN
1986-12-31               NaN
1987-12-31               NaN
1988-12-31               NaN
1989-12-31               NaN
1990-12-31      5.282716e+09
1991-12-31               NaN
1992-12-31               NaN
1993-12-31               NaN
1994-12-31               NaN
1995-12-31               NaN
1996-12-31               NaN
1997-12-31               NaN
1998-12-31               NaN
1999-12-31               NaN
2000-12-31      6.115974e+09
2001-12-31               NaN
2002-12-31               NaN
2003-12-31               NaN
2004-12-31               NaN
2005-12-31               NaN
2006-12-31               NaN
2007-12-31               NaN
2008-12-31               NaN
2009-12-31               NaN
2010-12-31      6.924283e+09

In [3]:
# Interpolate missing data
population.resample('A').first().interpolate('linear')

            Total Population
Year
1960-12-31      3.034971e+09
1961-12-31      3.099956e+09
1962-12-31      3.164941e+09
1963-12-31      3.229926e+09
1964-12-31      3.294911e+09
1965-12-31      3.359897e+09
1966-12-31      3.424882e+09
1967-12-31      3.489867e+09
1968-12-31      3.554852e+09
1969-12-31      3.619837e+09
1970-12-31      3.684823e+09
1971-12-31      3.759999e+09
1972-12-31      3.835176e+09
1973-12-31      3.910353e+09
1974-12-31      3.985530e+09
1975-12-31      4.060707e+09
1976-12-31      4.135883e+09
1977-12-31      4.211060e+09
1978-12-31      4.286237e+09
1979-12-31      4.361414e+09
1980-12-31      4.436590e+09
1981-12-31      4.521203e+09
1982-12-31      4.605815e+09
1983-12-31      4.690428e+09
1984-12-31      4.775041e+09
1985-12-31      4.859653e+09
1986-12-31      4.944266e+09
1987-12-31      5.028878e+09
1988-12-31      5.113491e+09
1989-12-31      5.198103e+09
1990-12-31      5.282716e+09
1991-12-31      5.366042e+09
1992-12-31      5.449368e+09
1993-12-31      5.532694e+09
1994-12-31      5.616019e+09
1995-12-31      5.699345e+09
1996-12-31      5.782671e+09
1997-12-31      5.865997e+09
1998-12-31      5.949323e+09
1999-12-31      6.032649e+09
2000-12-31      6.115974e+09
2001-12-31      6.196805e+09
2002-12-31      6.277636e+09
2003-12-31      6.358467e+09
2004-12-31      6.439298e+09
2005-12-31      6.520129e+09
2006-12-31      6.600960e+09
2007-12-31      6.681790e+09
2008-12-31      6.762621e+09
2009-12-31      6.843452e+09
2010-12-31      6.924283e+09